language:
    node_js
node_js:
    - 0.10
branches:
    only:
        - master
        - develop
before_script:
    # install dependencies
    - gem update --system
    - gem uninstall sass
    - gem install sass
    - gem install compass
    - npm install -g grunt-cli bower
    - bower install
script:
    # We want to gate on passing tests and a successful build
    - grunt
